"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Loader2, CheckCircle2, XCircle } from "lucide-react";
import { highlightDDL } from "@/lib/highlight-ddl";

type Phase = "preview" | "success" | "error";

interface SqlPreviewDialogProps {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  sql: string;
  /** When provided, shows an "Online" checkbox that switches to this SQL variant. */
  sqlOnline?: string;
  onSuccess: () => void;
}

export default function SqlPreviewDialog({
  open,
  onOpenChange,
  sql,
  sqlOnline,
  onSuccess,
}: SqlPreviewDialogProps) {
  const [executing, setExecuting] = useState(false);
  const [phase, setPhase] = useState<Phase>("preview");
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [online, setOnline] = useState(false);

  const activeSql = online && sqlOnline ? sqlOnline : sql;

  async function handleConfirm() {
    setExecuting(true);
    try {
      const res = await fetch("/api/schema/execute-ddl", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sql: activeSql }),
      });
      const data = await res.json();
      if (!res.ok || data.error) {
        setErrorMsg(data.error ?? "Execution failed");
        setPhase("error");
      } else {
        setPhase("success");
      }
    } catch {
      setErrorMsg("Network error — could not reach the server");
      setPhase("error");
    } finally {
      setExecuting(false);
    }
  }

  function handleDismiss() {
    if (phase === "success") onSuccess();
    setPhase("preview");
    setErrorMsg(null);
    setOnline(false);
    onOpenChange(false);
  }

  function handleOpenChange(v: boolean) {
    if (!executing) {
      if (!v) handleDismiss();
      else onOpenChange(v);
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-2xl">
        {phase === "preview" && (
          <>
            <DialogHeader>
              <DialogTitle>Preview &amp; Execute DDL</DialogTitle>
            </DialogHeader>

            <div className="rounded overflow-auto max-h-72">
              <pre
                className="p-3 bg-zinc-900 text-xs font-mono whitespace-pre"
                // Safe: sql is generated by DDL builders in sql-queries.ts using quoteId().
                // highlightDDL escapes &, <, > before injecting HTML.
                dangerouslySetInnerHTML={{ __html: highlightDDL(activeSql) }}
              />
            </div>

            {sqlOnline && (
              <label className="flex items-center gap-2 cursor-pointer w-fit">
                <input
                  type="checkbox"
                  checked={online}
                  onChange={(e) => setOnline(e.target.checked)}
                  className="h-3.5 w-3.5 accent-primary"
                />
                <span className="text-xs">
                  Online{" "}
                  <span className="text-muted-foreground">
                    (WITH ONLINE = ON — requires Enterprise edition)
                  </span>
                </span>
              </label>
            )}

            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => handleOpenChange(false)}
                disabled={executing}
              >
                Cancel
              </Button>
              <Button variant="destructive" onClick={handleConfirm} disabled={executing}>
                {executing && <Loader2 className="h-3 w-3 mr-1 animate-spin" />}
                Confirm &amp; Execute
              </Button>
            </DialogFooter>
          </>
        )}

        {phase === "success" && (
          <>
            <DialogHeader>
              <DialogTitle>Operation Complete</DialogTitle>
            </DialogHeader>

            <div className="flex flex-col items-center gap-3 py-4">
              <CheckCircle2 className="h-12 w-12 text-green-500" />
              <p className="text-sm text-center">The DDL was executed successfully.</p>
            </div>

            <DialogFooter>
              <Button onClick={handleDismiss}>OK</Button>
            </DialogFooter>
          </>
        )}

        {phase === "error" && (
          <>
            <DialogHeader>
              <DialogTitle>Execution Failed</DialogTitle>
            </DialogHeader>

            <div className="flex flex-col items-center gap-3 py-4">
              <XCircle className="h-12 w-12 text-destructive" />
              <p className="text-sm text-center text-destructive">{errorMsg}</p>
            </div>

            <DialogFooter>
              <Button variant="outline" onClick={() => setPhase("preview")}>
                Back
              </Button>
              <Button variant="destructive" onClick={handleDismiss}>
                Close
              </Button>
            </DialogFooter>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}
