import type { TableColumnDetail, IndexInfo } from "@/types/analysis";
import type { DdlBuilders } from "../../types";
import { quoteId } from "./queries";

const CHAR_TYPES = ["char", "character", "character varying", "varchar", "text"];

const SIZED_TYPES = ["char", "character", "character varying", "varchar", "bit", "bit varying"];

function formatDataType(col: TableColumnDetail): string {
  const t = col.dataType.toLowerCase();
  if (SIZED_TYPES.includes(t) && col.maxLength != null && col.maxLength > 0) {
    return `${col.dataType}(${col.maxLength})`;
  }
  if (["numeric", "decimal"].includes(t)) {
    if (col.numericPrecision != null && col.numericScale != null) {
      return `${col.dataType}(${col.numericPrecision}, ${col.numericScale})`;
    }
  }
  return col.dataType;
}

function esc(value: string): string {
  return value.replace(/'/g, "''");
}

function qualified(schema: string, table: string): string {
  return `${quoteId(schema)}.${quoteId(table)}`;
}

export const postgresDdl: DdlBuilders = {
  formatDataType,

  isCollatableType: (dataType) => CHAR_TYPES.includes(dataType.split("(")[0].toLowerCase().trim()),

  createTable(schema, tableName, columns, extended) {
    const lines: string[] = columns.map((col) => {
      const ext = extended?.get(col.columnName);
      if (ext?.isComputed && ext.computedDefinition) {
        // Postgres generated columns are always STORED.
        return `  ${quoteId(col.columnName)} ${formatDataType(col)} GENERATED ALWAYS AS (${ext.computedDefinition}) STORED`;
      }
      const parts: string[] = [`  ${quoteId(col.columnName)}`, formatDataType(col)];
      if (col.isIdentity) parts.push("GENERATED BY DEFAULT AS IDENTITY");
      parts.push(col.isNullable ? "NULL" : "NOT NULL");
      // An identity column supplies its own default.
      if (col.columnDefault != null && !col.isIdentity) parts.push(`DEFAULT ${col.columnDefault}`);
      return parts.join(" ");
    });

    const pkCols = columns.filter(
      (c) => c.isPrimaryKey && !extended?.get(c.columnName)?.isComputed
    );
    if (pkCols.length > 0) {
      const pkColList = pkCols.map((c) => quoteId(c.columnName)).join(", ");
      lines.push(`  CONSTRAINT ${quoteId("PK_" + tableName)} PRIMARY KEY (${pkColList})`);
    }

    return `CREATE TABLE ${qualified(schema, tableName)} (\n${lines.join(",\n")}\n);`;
  },

  indexes(schema, tableName, indexes: IndexInfo[]) {
    const statements: string[] = [];

    for (const idx of indexes) {
      // The PK's backing index is already covered by CREATE TABLE.
      if (idx.isPrimaryKey) continue;

      const keyCols = idx.columns
        .filter((c) => !c.isIncluded)
        .sort((a, b) => a.keyOrdinal - b.keyOrdinal)
        .map((c) => quoteId(c.name));
      if (keyCols.length === 0) continue;

      const includedCols = idx.columns.filter((c) => c.isIncluded).map((c) => quoteId(c.name));

      const unique = idx.isUnique ? "UNIQUE " : "";
      const using = idx.type && idx.type.toUpperCase() !== "NONCLUSTERED" ? ` USING ${idx.type.toLowerCase()}` : "";
      let stmt = `CREATE ${unique}INDEX ${quoteId(idx.indexName)}\n    ON ${qualified(schema, tableName)}${using} (${keyCols.join(", ")})`;
      if (includedCols.length > 0) stmt += `\n    INCLUDE (${includedCols.join(", ")})`;
      if (idx.filterDefinition) stmt += `\n    WHERE ${idx.filterDefinition}`;
      stmt += ";";
      if (idx.isDisabled) stmt += "  -- INVALID";

      statements.push(stmt);
    }

    return statements.join("\n\n");
  },

  missingIndex(equalityColumns, inequalityColumns, includedColumns, schema, tableName, idx) {
    const parts: string[] = [];
    if (equalityColumns) parts.push(equalityColumns);
    if (inequalityColumns) parts.push(inequalityColumns);
    const include = includedColumns ? ` INCLUDE (${includedColumns})` : "";
    return `CREATE INDEX ${quoteId(`IX_Missing_${idx}`)}\nON ${qualified(schema, tableName)} (${parts.join(", ")})${include};`;
  },

  alterColumn(schema, tableName, colName, dataTypeFull, isNullable, collation) {
    // Postgres splits what T-SQL does in one ALTER COLUMN into separate statements.
    const target = `ALTER TABLE ${qualified(schema, tableName)} ALTER COLUMN ${quoteId(colName)}`;
    const collatePart = collation ? ` COLLATE ${quoteId(collation)}` : "";
    return [
      `${target} TYPE ${dataTypeFull}${collatePart};`,
      `${target} ${isNullable ? "DROP" : "SET"} NOT NULL;`,
    ].join("\n");
  },

  setDefault(schema, tableName, colName, _oldConstraintName, newDefault) {
    const target = `ALTER TABLE ${qualified(schema, tableName)} ALTER COLUMN ${quoteId(colName)}`;
    return newDefault && newDefault.trim()
      ? `${target} SET DEFAULT ${newDefault};`
      : `${target} DROP DEFAULT;`;
  },

  columnComment(schema, tableName, colName, comment) {
    return `COMMENT ON COLUMN ${qualified(schema, tableName)}.${quoteId(colName)} IS '${esc(comment)}';`;
  },

  dropIndex(schema, _tableName, indexName) {
    // Index names are schema-scoped in Postgres; the table is not named.
    return `DROP INDEX ${quoteId(schema)}.${quoteId(indexName)};`;
  },

  alterIndex(schema, _tableName, indexName, action) {
    if (action === "DISABLE") {
      throw new Error("PostgreSQL does not support disabling an index");
    }
    return `REINDEX INDEX ${quoteId(schema)}.${quoteId(indexName)};`;
  },

  dropConstraint(schema, tableName, constraintName) {
    return `ALTER TABLE ${qualified(schema, tableName)} DROP CONSTRAINT ${quoteId(constraintName)};`;
  },

  renameColumn(schema, tableName, oldName, newName) {
    return `ALTER TABLE ${qualified(schema, tableName)} RENAME COLUMN ${quoteId(oldName)} TO ${quoteId(newName)};`;
  },

  allowedStatementPrefixes: [
    "ALTER TABLE ",
    "DROP INDEX ",
    "CREATE INDEX ",
    "CREATE UNIQUE INDEX ",
    "REINDEX INDEX ",
    "COMMENT ON COLUMN ",
  ],
};
