-- Demo schema for exercising db-insight against PostgreSQL.
-- Uses two schemas so the sidebar's schema grouping has something to group.

CREATE SCHEMA IF NOT EXISTS sales;

CREATE TABLE public.customers (
    customer_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(120) NOT NULL,
    email        varchar(200),
    country      varchar(2)   NOT NULL DEFAULT 'US',
    created_at   timestamp    NOT NULL DEFAULT now()
);

COMMENT ON COLUMN public.customers.email IS 'Primary contact address';

CREATE TABLE public.products (
    product_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku          varchar(40)  NOT NULL,
    name         varchar(200) NOT NULL,
    unit_price   numeric(10, 2) NOT NULL,
    -- A generated column, so the DDL viewer has one to render
    price_with_tax numeric(12, 4) GENERATED ALWAYS AS (unit_price * 1.2) STORED,
    discontinued boolean NOT NULL DEFAULT false
);

CREATE UNIQUE INDEX ix_products_sku ON public.products (sku);
CREATE INDEX ix_products_price ON public.products (unit_price) INCLUDE (name);
-- A partial index, to exercise filtered-index rendering
CREATE INDEX ix_products_active ON public.products (name) WHERE NOT discontinued;

CREATE TABLE sales.orders (
    order_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  integer NOT NULL REFERENCES public.customers (customer_id) ON DELETE CASCADE,
    ordered_at   timestamp NOT NULL DEFAULT now(),
    total        numeric(12, 2) NOT NULL DEFAULT 0
);

CREATE INDEX ix_orders_customer ON sales.orders (customer_id);

CREATE TABLE sales.order_lines (
    order_line_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      integer NOT NULL REFERENCES sales.orders (order_id) ON DELETE CASCADE,
    product_id    integer NOT NULL REFERENCES public.products (product_id),
    quantity      integer NOT NULL DEFAULT 1,
    line_total    numeric(12, 2) NOT NULL
);

CREATE INDEX ix_order_lines_order ON sales.order_lines (order_id);

CREATE VIEW public.v_customer_totals AS
SELECT c.customer_id, c.name, COUNT(o.order_id) AS order_count, COALESCE(SUM(o.total), 0) AS lifetime_value
FROM public.customers c
LEFT JOIN sales.orders o ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.name;

CREATE FUNCTION public.customer_order_count(p_customer_id integer)
RETURNS integer
LANGUAGE sql
AS $$
    SELECT COUNT(*)::int FROM sales.orders WHERE customer_id = p_customer_id;
$$;

CREATE PROCEDURE sales.recalculate_order_total(p_order_id integer)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE sales.orders o
    SET total = COALESCE((SELECT SUM(line_total) FROM sales.order_lines WHERE order_id = o.order_id), 0)
    WHERE o.order_id = p_order_id;
END;
$$;

INSERT INTO public.customers (name, email, country)
SELECT 'Customer ' || i, 'customer' || i || '@example.com', CASE WHEN i % 3 = 0 THEN 'GB' ELSE 'US' END
FROM generate_series(1, 500) AS i;

INSERT INTO public.products (sku, name, unit_price, discontinued)
SELECT 'SKU-' || lpad(i::text, 5, '0'), 'Product ' || i, (i % 200) + 9.99, i % 17 = 0
FROM generate_series(1, 300) AS i;

INSERT INTO sales.orders (customer_id, total)
SELECT (i % 500) + 1, 0
FROM generate_series(1, 2000) AS i;

INSERT INTO sales.order_lines (order_id, product_id, quantity, line_total)
SELECT (i % 2000) + 1, (i % 300) + 1, (i % 5) + 1, ((i % 5) + 1) * (((i % 200) + 9.99))
FROM generate_series(1, 6000) AS i;

UPDATE sales.orders o
SET total = COALESCE((SELECT SUM(line_total) FROM sales.order_lines WHERE order_id = o.order_id), 0);

-- Populate planner statistics so the row-count estimates are not zero
ANALYZE;
